### PR TITLE
Milestone 1: Finished Form Feature

### PR DESCRIPTION
**Pull request by Bismarck-GM**
## Milestone 1: Finished Form Feature

In this Milestone we:

- Created a Form.
- Used SVG logos for the header of the form.
- Used proper form element types.
- Cloned the styles of the page so it looks like Mint's original one.

### CODE REVIEW

**Review by davidmrtz-dev — CHANGES_REQUESTED** [review]
## Hi Team. 👨‍🚀  
### Very good job so far.
* Your README file is clear and descriptive.
* Your pull request and commits messages are clear and descriptive.
* The Html Validator doesn't drop any warning or error.
* Correctly added Stickler.
However, the following issues need to be implemented/fixed to consider this project as approved  👨‍💻  ⬇️ 

****

- [x] Spacing and position of "sign up" button.

The signup button looks good, but we can improve it, please add the spacing between the button and the top and right of the page.
Descriptive images below.
How it looks now. ⬇️ 
Screen Shot 2020-05-02 at 6 49 17 PM

The example on which the project is based. ⬇️ 
Screen Shot 2020-05-02 at 6 49 31 PM

****
- [x] Spacing between logos.

On the given page there's a space between each logo and the text and color, kindly please add this spacing following the given page.
How it looks now. ⬇️ 
Screen Shot 2020-05-02 at 6 52 52 PM

The example on which the project is based. ⬇️ 
Screen Shot 2020-05-02 at 6 53 00 PM

****
- [x] Form.

Kindly please check the following list.

1. Reduce the size of the text to be one line like the given page.

Your page: ⬇️ 
Screen Shot 2020-05-02 at 6 54 51 PM

The example on which the project is based. ⬇️ 

Screen Shot 2020-05-02 at 6 54 58 PM

2. The size of the text "Standard call, messaging or data rates may apply." must be smaller than the labels text.

3. The password input has to be the same size as the other user input fields.

4. Kindly please style and modify the captcha section following the design and the color of the given page, use the 100% width of the parent container.

5. The "create account" button should be the same size on width as the input fields.

Your page: ⬇️ 
Screen Shot 2020-05-02 at 6 56 53 PM

The example on which the project is based. ⬇️ 
Screen Shot 2020-05-02 at 6 57 27 PM

****

### **Please kindly make the changes required and submit for re-review once you are ready!** 🙏 

****

### Status: Changes required. ♻️  👀 
****

Happy coding! 😄 💻  


**[TSE:  David Elí]** 👨‍💻 
Slack: @ David Eli Martinez Garcia

**Comment by Bismarck-GM** [comment]
If we correct those Linter errors the Styles will break because the Browser will use **Default Settings.**

I already corrected some and noticed the lack of margins within the header. So we'll need to correct that.

Let's check how to manage this kind of thing tomorrow!

**Comment by Bismarck-GM** [comment]
My mistake on the errors it was asking.

I thought it was asking me to put a measuring unit after de 0's and made a mess with them.

If you want to declare something 0 is just `property: 0; ` 

I.e. `border: 1px solid #4c4c4c;`

**Comment by Bismarck-GM** [comment]
## Code review 1 ## 

In this code review we changed:
- Corrected margins at the top-right button and footer anchor tags.
- Corrected the "lock" in password input.
- Added form-footer div (the grey one) to be a piece of the form.
- Changed the Password input so it behaves like all other's inputs.

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @Bismarck-GM and @santiagorodriguezbermudez, you did a great job fixing the changes recommended by the previous TSE :+1:  However, I found a few  I would like you to address, kindly find comments below:
- Kindly removed commented code
cc
- Kindly avoid using tag names for styling, we use ```classes``` for styling
- Kindly apply the DRY rule so we do not repeat code in our CSS file. This [article](https://speckyboy.com/good-bad-css-practices/) would help
- Kindly increase the width of the form so it looks like the original

Kindly fix these and submit another code review :smile: 
_Happy coding_ :man_technologist: 
Daniel Larbi Addo on slack

**Comment by Bismarck-GM** [comment]
## Code review 2 ##
In this code review we changed:

- Deleted HTML commented code.
- Added classes for tags.
- Increased width of form to be fixed.

**Review by mikenath223 — APPROVED** [review]
### CONGRATULATIONS  TEAM 👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**


Don't forget to fill the project completion form👍
Good luck with the next project.

TSE(Michgolden Ukeje)

HAPPY CODING👨‍💻

**Pull request merged**
